// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "kernel6.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic kernel6::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic kernel6::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<5> kernel6::ap_ST_fsm_state1 = "1";
const sc_lv<5> kernel6::ap_ST_fsm_state2 = "10";
const sc_lv<5> kernel6::ap_ST_fsm_state3 = "100";
const sc_lv<5> kernel6::ap_ST_fsm_pp0_stage0 = "1000";
const sc_lv<5> kernel6::ap_ST_fsm_state6 = "10000";
const sc_lv<32> kernel6::ap_const_lv32_0 = "00000000000000000000000000000000";
const bool kernel6::ap_const_boolean_1 = true;
const sc_lv<32> kernel6::ap_const_lv32_1 = "1";
const sc_lv<1> kernel6::ap_const_lv1_0 = "0";
const sc_lv<32> kernel6::ap_const_lv32_2 = "10";
const sc_lv<32> kernel6::ap_const_lv32_3 = "11";
const bool kernel6::ap_const_boolean_0 = false;
const sc_lv<1> kernel6::ap_const_lv1_1 = "1";
const sc_lv<12> kernel6::ap_const_lv12_0 = "000000000000";
const sc_lv<32> kernel6::ap_const_lv32_4 = "100";
const sc_lv<31> kernel6::ap_const_lv31_0 = "0000000000000000000000000000000";
const sc_lv<12> kernel6::ap_const_lv12_800 = "100000000000";
const sc_lv<12> kernel6::ap_const_lv12_1 = "1";
const sc_lv<31> kernel6::ap_const_lv31_1 = "1";

kernel6::kernel6(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_add_ln15_fu_183_p2);
    sensitive << ( start_reg_226 );
    sensitive << ( zext_ln11_fu_168_p1 );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_11001);

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state5_pp0_stage0_iter1);

    SC_METHOD(thread_ap_condition_pp0_exit_iter0_state4);
    sensitive << ( icmp_ln11_fu_172_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln4_fu_149_p2 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln4_fu_149_p2 );

    SC_METHOD(thread_i_fu_155_p2);
    sensitive << ( i_0_reg_114 );

    SC_METHOD(thread_icmp_ln11_fu_172_p2);
    sensitive << ( len_reg_231 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( zext_ln11_fu_168_p1 );

    SC_METHOD(thread_icmp_ln4_fu_149_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( i_0_reg_114 );

    SC_METHOD(thread_index_dst_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( zext_ln6_fu_161_p1 );

    SC_METHOD(thread_index_dst_ce0);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_j_fu_177_p2);
    sensitive << ( j_0_reg_138 );

    SC_METHOD(thread_region_len_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( zext_ln6_fu_161_p1 );

    SC_METHOD(thread_region_len_ce0);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_region_start_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( zext_ln6_fu_161_p1 );

    SC_METHOD(thread_region_start_ce0);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_results_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( sext_ln15_fu_188_p1 );
    sensitive << ( sext_ln17_fu_199_p1 );

    SC_METHOD(thread_results_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_results_d0);
    sensitive << ( sum_0_reg_125 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_results_we0);
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_sext_ln15_fu_188_p1);
    sensitive << ( add_ln15_fu_183_p2 );

    SC_METHOD(thread_sext_ln17_fu_199_p1);
    sensitive << ( dst_reg_236 );

    SC_METHOD(thread_sum_fu_193_p2);
    sensitive << ( results_q0 );
    sensitive << ( sum_0_reg_125 );

    SC_METHOD(thread_zext_ln11_fu_168_p1);
    sensitive << ( j_0_reg_138 );

    SC_METHOD(thread_zext_ln6_fu_161_p1);
    sensitive << ( i_0_reg_114 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln4_fu_149_p2 );
    sensitive << ( icmp_ln11_fu_172_p2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0_subdone );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    ap_CS_fsm = "00001";
    ap_enable_reg_pp0_iter0 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "kernel6_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, region_start_address0, "(port)region_start_address0");
    sc_trace(mVcdFile, region_start_ce0, "(port)region_start_ce0");
    sc_trace(mVcdFile, region_start_q0, "(port)region_start_q0");
    sc_trace(mVcdFile, region_len_address0, "(port)region_len_address0");
    sc_trace(mVcdFile, region_len_ce0, "(port)region_len_ce0");
    sc_trace(mVcdFile, region_len_q0, "(port)region_len_q0");
    sc_trace(mVcdFile, index_dst_address0, "(port)index_dst_address0");
    sc_trace(mVcdFile, index_dst_ce0, "(port)index_dst_ce0");
    sc_trace(mVcdFile, index_dst_q0, "(port)index_dst_q0");
    sc_trace(mVcdFile, results_address0, "(port)results_address0");
    sc_trace(mVcdFile, results_ce0, "(port)results_ce0");
    sc_trace(mVcdFile, results_we0, "(port)results_we0");
    sc_trace(mVcdFile, results_d0, "(port)results_d0");
    sc_trace(mVcdFile, results_q0, "(port)results_q0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, sum_0_reg_125, "sum_0_reg_125");
    sc_trace(mVcdFile, j_0_reg_138, "j_0_reg_138");
    sc_trace(mVcdFile, i_fu_155_p2, "i_fu_155_p2");
    sc_trace(mVcdFile, i_reg_206, "i_reg_206");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, icmp_ln4_fu_149_p2, "icmp_ln4_fu_149_p2");
    sc_trace(mVcdFile, start_reg_226, "start_reg_226");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, len_reg_231, "len_reg_231");
    sc_trace(mVcdFile, dst_reg_236, "dst_reg_236");
    sc_trace(mVcdFile, icmp_ln11_fu_172_p2, "icmp_ln11_fu_172_p2");
    sc_trace(mVcdFile, icmp_ln11_reg_241, "icmp_ln11_reg_241");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter0, "ap_block_state4_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state5_pp0_stage0_iter1, "ap_block_state5_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, j_fu_177_p2, "j_fu_177_p2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, sum_fu_193_p2, "sum_fu_193_p2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp0_exit_iter0_state4, "ap_condition_pp0_exit_iter0_state4");
    sc_trace(mVcdFile, i_0_reg_114, "i_0_reg_114");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, zext_ln6_fu_161_p1, "zext_ln6_fu_161_p1");
    sc_trace(mVcdFile, sext_ln15_fu_188_p1, "sext_ln15_fu_188_p1");
    sc_trace(mVcdFile, sext_ln17_fu_199_p1, "sext_ln17_fu_199_p1");
    sc_trace(mVcdFile, zext_ln11_fu_168_p1, "zext_ln11_fu_168_p1");
    sc_trace(mVcdFile, add_ln15_fu_183_p2, "add_ln15_fu_183_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
#endif

    }
    mHdltvinHandle.open("kernel6.hdltvin.dat");
    mHdltvoutHandle.open("kernel6.hdltvout.dat");
}

kernel6::~kernel6() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
}

void kernel6::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state4.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_0;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state4.read()))) {
            ap_enable_reg_pp0_iter1 = (ap_condition_pp0_exit_iter0_state4.read() ^ ap_const_logic_1);
        } else if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter1 = ap_enable_reg_pp0_iter0.read();
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
            ap_enable_reg_pp0_iter1 = ap_const_logic_0;
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        i_0_reg_114 = i_reg_206.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        i_0_reg_114 = ap_const_lv12_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(icmp_ln11_fu_172_p2.read(), ap_const_lv1_1))) {
        j_0_reg_138 = j_fu_177_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        j_0_reg_138 = ap_const_lv31_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(icmp_ln11_reg_241.read(), ap_const_lv1_1))) {
        sum_0_reg_125 = sum_fu_193_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        sum_0_reg_125 = ap_const_lv32_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        dst_reg_236 = index_dst_q0.read();
        len_reg_231 = region_len_q0.read();
        start_reg_226 = region_start_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        i_reg_206 = i_fu_155_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        icmp_ln11_reg_241 = icmp_ln11_fu_172_p2.read();
    }
}

void kernel6::thread_add_ln15_fu_183_p2() {
    add_ln15_fu_183_p2 = (!start_reg_226.read().is_01() || !zext_ln11_fu_168_p1.read().is_01())? sc_lv<32>(): (sc_biguint<32>(start_reg_226.read()) + sc_biguint<32>(zext_ln11_fu_168_p1.read()));
}

void kernel6::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[3];
}

void kernel6::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void kernel6::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void kernel6::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void kernel6::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[4];
}

void kernel6::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void kernel6::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void kernel6::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void kernel6::thread_ap_block_state4_pp0_stage0_iter0() {
    ap_block_state4_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void kernel6::thread_ap_block_state5_pp0_stage0_iter1() {
    ap_block_state5_pp0_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void kernel6::thread_ap_condition_pp0_exit_iter0_state4() {
    if (esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln11_fu_172_p2.read())) {
        ap_condition_pp0_exit_iter0_state4 = ap_const_logic_1;
    } else {
        ap_condition_pp0_exit_iter0_state4 = ap_const_logic_0;
    }
}

void kernel6::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln4_fu_149_p2.read(), ap_const_lv1_1))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void kernel6::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void kernel6::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void kernel6::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void kernel6::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln4_fu_149_p2.read(), ap_const_lv1_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void kernel6::thread_i_fu_155_p2() {
    i_fu_155_p2 = (!i_0_reg_114.read().is_01() || !ap_const_lv12_1.is_01())? sc_lv<12>(): (sc_biguint<12>(i_0_reg_114.read()) + sc_biguint<12>(ap_const_lv12_1));
}

void kernel6::thread_icmp_ln11_fu_172_p2() {
    icmp_ln11_fu_172_p2 = (!zext_ln11_fu_168_p1.read().is_01() || !len_reg_231.read().is_01())? sc_lv<1>(): (sc_bigint<32>(zext_ln11_fu_168_p1.read()) < sc_bigint<32>(len_reg_231.read()));
}

void kernel6::thread_icmp_ln4_fu_149_p2() {
    icmp_ln4_fu_149_p2 = (!i_0_reg_114.read().is_01() || !ap_const_lv12_800.is_01())? sc_lv<1>(): sc_lv<1>(i_0_reg_114.read() == ap_const_lv12_800);
}

void kernel6::thread_index_dst_address0() {
    index_dst_address0 =  (sc_lv<11>) (zext_ln6_fu_161_p1.read());
}

void kernel6::thread_index_dst_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        index_dst_ce0 = ap_const_logic_1;
    } else {
        index_dst_ce0 = ap_const_logic_0;
    }
}

void kernel6::thread_j_fu_177_p2() {
    j_fu_177_p2 = (!j_0_reg_138.read().is_01() || !ap_const_lv31_1.is_01())? sc_lv<31>(): (sc_biguint<31>(j_0_reg_138.read()) + sc_biguint<31>(ap_const_lv31_1));
}

void kernel6::thread_region_len_address0() {
    region_len_address0 =  (sc_lv<11>) (zext_ln6_fu_161_p1.read());
}

void kernel6::thread_region_len_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        region_len_ce0 = ap_const_logic_1;
    } else {
        region_len_ce0 = ap_const_logic_0;
    }
}

void kernel6::thread_region_start_address0() {
    region_start_address0 =  (sc_lv<11>) (zext_ln6_fu_161_p1.read());
}

void kernel6::thread_region_start_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        region_start_ce0 = ap_const_logic_1;
    } else {
        region_start_ce0 = ap_const_logic_0;
    }
}

void kernel6::thread_results_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        results_address0 =  (sc_lv<12>) (sext_ln17_fu_199_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        results_address0 =  (sc_lv<12>) (sext_ln15_fu_188_p1.read());
    } else {
        results_address0 = "XXXXXXXXXXXX";
    }
}

void kernel6::thread_results_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()))) {
        results_ce0 = ap_const_logic_1;
    } else {
        results_ce0 = ap_const_logic_0;
    }
}

void kernel6::thread_results_d0() {
    results_d0 = sum_0_reg_125.read();
}

void kernel6::thread_results_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        results_we0 = ap_const_logic_1;
    } else {
        results_we0 = ap_const_logic_0;
    }
}

void kernel6::thread_sext_ln15_fu_188_p1() {
    sext_ln15_fu_188_p1 = esl_sext<64,32>(add_ln15_fu_183_p2.read());
}

void kernel6::thread_sext_ln17_fu_199_p1() {
    sext_ln17_fu_199_p1 = esl_sext<64,32>(dst_reg_236.read());
}

void kernel6::thread_sum_fu_193_p2() {
    sum_fu_193_p2 = (!results_q0.read().is_01() || !sum_0_reg_125.read().is_01())? sc_lv<32>(): (sc_biguint<32>(results_q0.read()) + sc_biguint<32>(sum_0_reg_125.read()));
}

void kernel6::thread_zext_ln11_fu_168_p1() {
    zext_ln11_fu_168_p1 = esl_zext<32,31>(j_0_reg_138.read());
}

void kernel6::thread_zext_ln6_fu_161_p1() {
    zext_ln6_fu_161_p1 = esl_zext<64,12>(i_0_reg_114.read());
}

void kernel6::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln4_fu_149_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            break;
        case 8 : 
            if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln11_fu_172_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln11_fu_172_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state6;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state2;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<5>) ("XXXXX");
            break;
    }
}

void kernel6::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"region_start_address0\" :  \"" << region_start_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"region_start_ce0\" :  \"" << region_start_ce0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"region_start_q0\" :  \"" << region_start_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"region_len_address0\" :  \"" << region_len_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"region_len_ce0\" :  \"" << region_len_ce0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"region_len_q0\" :  \"" << region_len_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"index_dst_address0\" :  \"" << index_dst_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"index_dst_ce0\" :  \"" << index_dst_ce0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"index_dst_q0\" :  \"" << index_dst_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"results_address0\" :  \"" << results_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"results_ce0\" :  \"" << results_ce0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"results_we0\" :  \"" << results_we0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"results_d0\" :  \"" << results_d0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"results_q0\" :  \"" << results_q0.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

