// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "kernel8.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic kernel8::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic kernel8::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<6> kernel8::ap_ST_fsm_state1 = "1";
const sc_lv<6> kernel8::ap_ST_fsm_state2 = "10";
const sc_lv<6> kernel8::ap_ST_fsm_state3 = "100";
const sc_lv<6> kernel8::ap_ST_fsm_state4 = "1000";
const sc_lv<6> kernel8::ap_ST_fsm_state5 = "10000";
const sc_lv<6> kernel8::ap_ST_fsm_state6 = "100000";
const sc_lv<32> kernel8::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> kernel8::ap_const_lv32_1 = "1";
const sc_lv<1> kernel8::ap_const_lv1_1 = "1";
const sc_lv<32> kernel8::ap_const_lv32_2 = "10";
const sc_lv<32> kernel8::ap_const_lv32_3 = "11";
const sc_lv<32> kernel8::ap_const_lv32_4 = "100";
const sc_lv<31> kernel8::ap_const_lv31_6 = "110";
const sc_lv<32> kernel8::ap_const_lv32_7FF = "11111111111";
const sc_lv<31> kernel8::ap_const_lv31_7FFFFFFA = "1111111111111111111111111111010";
const sc_lv<31> kernel8::ap_const_lv31_1 = "1";
const sc_lv<32> kernel8::ap_const_lv32_5 = "101";
const bool kernel8::ap_const_boolean_1 = true;

kernel8::kernel8(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_a_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( sext_ln9_fu_123_p1 );
    sensitive << ( zext_ln9_fu_132_p1 );

    SC_METHOD(thread_a_ce0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_a_d0);
    sensitive << ( mul_ln9_reg_171 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_a_we0);
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_add_ln9_1_fu_118_p2);
    sensitive << ( offset );
    sensitive << ( zext_ln9_1_fu_114_p1 );

    SC_METHOD(thread_add_ln9_fu_108_p2);
    sensitive << ( i_0_reg_81 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_i_fu_137_p2);
    sensitive << ( i_0_reg_81 );

    SC_METHOD(thread_icmp_ln5_fu_103_p2);
    sensitive << ( sub_ln5_reg_153 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( zext_ln5_fu_99_p1 );

    SC_METHOD(thread_mul_ln9_fu_128_p1);
    sensitive << ( factor );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_mul_ln9_fu_128_p2);
    sensitive << ( a_load_reg_166 );
    sensitive << ( mul_ln9_fu_128_p1 );

    SC_METHOD(thread_sext_ln9_fu_123_p1);
    sensitive << ( add_ln9_1_fu_118_p2 );

    SC_METHOD(thread_sub_ln5_fu_93_p2);
    sensitive << ( offset );

    SC_METHOD(thread_zext_ln5_fu_99_p1);
    sensitive << ( i_0_reg_81 );

    SC_METHOD(thread_zext_ln9_1_fu_114_p1);
    sensitive << ( add_ln9_fu_108_p2 );

    SC_METHOD(thread_zext_ln9_fu_132_p1);
    sensitive << ( i_0_reg_81 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln5_fu_103_p2 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    ap_CS_fsm = "000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "kernel8_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, a_address0, "(port)a_address0");
    sc_trace(mVcdFile, a_ce0, "(port)a_ce0");
    sc_trace(mVcdFile, a_we0, "(port)a_we0");
    sc_trace(mVcdFile, a_d0, "(port)a_d0");
    sc_trace(mVcdFile, a_q0, "(port)a_q0");
    sc_trace(mVcdFile, factor, "(port)factor");
    sc_trace(mVcdFile, offset, "(port)offset");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, sub_ln5_fu_93_p2, "sub_ln5_fu_93_p2");
    sc_trace(mVcdFile, sub_ln5_reg_153, "sub_ln5_reg_153");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, icmp_ln5_fu_103_p2, "icmp_ln5_fu_103_p2");
    sc_trace(mVcdFile, a_load_reg_166, "a_load_reg_166");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, mul_ln9_fu_128_p2, "mul_ln9_fu_128_p2");
    sc_trace(mVcdFile, mul_ln9_reg_171, "mul_ln9_reg_171");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, i_fu_137_p2, "i_fu_137_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, i_0_reg_81, "i_0_reg_81");
    sc_trace(mVcdFile, sext_ln9_fu_123_p1, "sext_ln9_fu_123_p1");
    sc_trace(mVcdFile, zext_ln9_fu_132_p1, "zext_ln9_fu_132_p1");
    sc_trace(mVcdFile, zext_ln5_fu_99_p1, "zext_ln5_fu_99_p1");
    sc_trace(mVcdFile, add_ln9_fu_108_p2, "add_ln9_fu_108_p2");
    sc_trace(mVcdFile, zext_ln9_1_fu_114_p1, "zext_ln9_1_fu_114_p1");
    sc_trace(mVcdFile, add_ln9_1_fu_118_p2, "add_ln9_1_fu_118_p2");
    sc_trace(mVcdFile, mul_ln9_fu_128_p1, "mul_ln9_fu_128_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("kernel8.hdltvin.dat");
    mHdltvoutHandle.open("kernel8.hdltvout.dat");
}

kernel8::~kernel8() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
}

void kernel8::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        i_0_reg_81 = i_fu_137_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        i_0_reg_81 = ap_const_lv31_6;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        a_load_reg_166 = a_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        mul_ln9_reg_171 = mul_ln9_fu_128_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        sub_ln5_reg_153 = sub_ln5_fu_93_p2.read();
    }
}

void kernel8::thread_a_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        a_address0 =  (sc_lv<11>) (zext_ln9_fu_132_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        a_address0 =  (sc_lv<11>) (sext_ln9_fu_123_p1.read());
    } else {
        a_address0 = "XXXXXXXXXXX";
    }
}

void kernel8::thread_a_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()))) {
        a_ce0 = ap_const_logic_1;
    } else {
        a_ce0 = ap_const_logic_0;
    }
}

void kernel8::thread_a_d0() {
    a_d0 = mul_ln9_reg_171.read();
}

void kernel8::thread_a_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        a_we0 = ap_const_logic_1;
    } else {
        a_we0 = ap_const_logic_0;
    }
}

void kernel8::thread_add_ln9_1_fu_118_p2() {
    add_ln9_1_fu_118_p2 = (!zext_ln9_1_fu_114_p1.read().is_01() || !offset.read().is_01())? sc_lv<32>(): (sc_biguint<32>(zext_ln9_1_fu_114_p1.read()) + sc_biguint<32>(offset.read()));
}

void kernel8::thread_add_ln9_fu_108_p2() {
    add_ln9_fu_108_p2 = (!i_0_reg_81.read().is_01() || !ap_const_lv31_7FFFFFFA.is_01())? sc_lv<31>(): (sc_biguint<31>(i_0_reg_81.read()) + sc_bigint<31>(ap_const_lv31_7FFFFFFA));
}

void kernel8::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void kernel8::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void kernel8::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void kernel8::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void kernel8::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void kernel8::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void kernel8::thread_ap_done() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void kernel8::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void kernel8::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void kernel8::thread_i_fu_137_p2() {
    i_fu_137_p2 = (!i_0_reg_81.read().is_01() || !ap_const_lv31_1.is_01())? sc_lv<31>(): (sc_biguint<31>(i_0_reg_81.read()) + sc_biguint<31>(ap_const_lv31_1));
}

void kernel8::thread_icmp_ln5_fu_103_p2() {
    icmp_ln5_fu_103_p2 = (!zext_ln5_fu_99_p1.read().is_01() || !sub_ln5_reg_153.read().is_01())? sc_lv<1>(): (sc_bigint<32>(zext_ln5_fu_99_p1.read()) < sc_bigint<32>(sub_ln5_reg_153.read()));
}

void kernel8::thread_mul_ln9_fu_128_p1() {
    mul_ln9_fu_128_p1 = factor.read();
}

void kernel8::thread_mul_ln9_fu_128_p2() {
    mul_ln9_fu_128_p2 = (!a_load_reg_166.read().is_01() || !mul_ln9_fu_128_p1.read().is_01())? sc_lv<32>(): sc_bigint<32>(a_load_reg_166.read()) * sc_bigint<32>(mul_ln9_fu_128_p1.read());
}

void kernel8::thread_sext_ln9_fu_123_p1() {
    sext_ln9_fu_123_p1 = esl_sext<64,32>(add_ln9_1_fu_118_p2.read());
}

void kernel8::thread_sub_ln5_fu_93_p2() {
    sub_ln5_fu_93_p2 = (!ap_const_lv32_7FF.is_01() || !offset.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_7FF) - sc_biguint<32>(offset.read()));
}

void kernel8::thread_zext_ln5_fu_99_p1() {
    zext_ln5_fu_99_p1 = esl_zext<32,31>(i_0_reg_81.read());
}

void kernel8::thread_zext_ln9_1_fu_114_p1() {
    zext_ln9_1_fu_114_p1 = esl_zext<32,31>(add_ln9_fu_108_p2.read());
}

void kernel8::thread_zext_ln9_fu_132_p1() {
    zext_ln9_fu_132_p1 = esl_zext<64,31>(i_0_reg_81.read());
}

void kernel8::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln5_fu_103_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state6;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state2;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<6>) ("XXXXXX");
            break;
    }
}

void kernel8::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"a_address0\" :  \"" << a_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"a_ce0\" :  \"" << a_ce0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"a_we0\" :  \"" << a_we0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"a_d0\" :  \"" << a_d0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"a_q0\" :  \"" << a_q0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"factor\" :  \"" << factor.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"offset\" :  \"" << offset.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

